#! usr/bin/env php
<?php

namespace Creational\FactoryMethod;

require_once 'vendor/autoload.php';

$factory = new FactoryMethod();

try {
    $firstProduct = $factory->create(FirstAbstractProduct::class);
    $secondProduct = $factory->create(SecondAbstractProduct::class);

    printf('%s'.PHP_EOL, $firstProduct->getClassName());
    printf('%s'.PHP_EOL, $secondProduct->getClassName());
} catch (\Exception $e) {
    echo 'Caught exception: ', $e->getMessage(), "\n";
}
